// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtNJoylPVtusUCbN8HDkrRnnRyfawuhQI',
    appId: '1:1044437569705:web:e60ab6c8c76a338da8d9b8',
    messagingSenderId: '1044437569705',
    projectId: 'chat-go-f1265',
    authDomain: 'chat-go-f1265.firebaseapp.com',
    storageBucket: 'chat-go-f1265.appspot.com',
    measurementId: 'G-B773JC9FB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAoeva3_rPHDoHtUdSXkBT2ziOtCBUCFM',
    appId: '1:1044437569705:android:b49593673da7ff5fa8d9b8',
    messagingSenderId: '1044437569705',
    projectId: 'chat-go-f1265',
    storageBucket: 'chat-go-f1265.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPzwP611Gf3lQWOXjDSrDuv8cUnLCE01M',
    appId: '1:1044437569705:ios:35f599bcdf67c1f7a8d9b8',
    messagingSenderId: '1044437569705',
    projectId: 'chat-go-f1265',
    storageBucket: 'chat-go-f1265.appspot.com',
    iosClientId: '1044437569705-r3btrji4t1bgcg70cv2jgbjlpd210vbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatgoclient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPzwP611Gf3lQWOXjDSrDuv8cUnLCE01M',
    appId: '1:1044437569705:ios:35f599bcdf67c1f7a8d9b8',
    messagingSenderId: '1044437569705',
    projectId: 'chat-go-f1265',
    storageBucket: 'chat-go-f1265.appspot.com',
    iosClientId: '1044437569705-r3btrji4t1bgcg70cv2jgbjlpd210vbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatgoclient',
  );
}
